version: '3.4'

services:

  testcasedb:
    container_name: testcasedb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017"



  testcaseappointmentsapi:
    container_name: testcaseappointmentsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AppoinmentsSettings:ConnectionString=mongodb://testcasedb:27017"
    depends_on:
        - testcasedb
        - testcaseapi
    ports:
      - "8003:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/



  testcasecsvapi:
    container_name: testcasecsvapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CSVDatabaseSettings:ConnectionString=mongodb://testcasedb:27017"
      - "ApplicationSettings:AppoinmentServiceUrl=http://testcaseappointmentsapi/api/v1/Appointments"
      - "ApplicationSettings:AuthUrl=http://testcaseapi/api/v1/Account/login"
    depends_on:
        - testcasedb
        - testcaseapi
        - testcaseappointmentsapi
    ports:
      - "8002:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/



  testcaseapi:
    container_name: testcaseapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "UserDatabaseSettings:ConnectionString=mongodb://testcasedb:27017"
      - xpack.security.enabled=false
    depends_on:
        - testcasedb
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
